MystenLabs/ts-sdks

.changeset/fresh-drinks-itch.md
packages/build-scripts/src/utils/buildPackage.ts
packages/typescript/src/cryptography/publickey.ts
packages/typescript/src/cryptography/signature.ts
packages/typescript/src/keypairs/ed25519/publickey.ts
packages/typescript/src/keypairs/secp256k1/publickey.ts

simplify number of imports needed when importing keypairs

---

packages/docs/pages/typescript/cryptography/keypairs.mdx

Adding a "!" to a block of example code where I'm *pretty* sure it's supposed to go.
I'll be honest, I didn't test it. I just read it and I'm pretty sure it needs this.
---

ya missed an exclamation mark

---

packages/walrus/src/utils/bcs.ts
packages/walrus/src/utils/index.ts

Add basic BCS types and utils to walrus sdk

---

.changeset/slimy-lobsters-live.md
packages/bcs/src/bcs-type.ts
packages/bcs/tests/builder.test.ts

[bcs] allow type transforms to omit input or output transforms

---

packages/seal/.prettierignore
packages/seal/README.md
packages/seal/examples/encrypt.ts
packages/seal/examples/tsconfig.json
packages/seal/package.json
packages/seal/src/constants.ts
packages/seal/src/index.ts
packages/seal/tests/encrypt.test.ts
packages/seal/tsconfig.esm.json
packages/seal/tsconfig.json
packages/seal/typedoc.json
packages/seal/vitest.config.mts
pnpm-lock.yaml

init package
```
pnpm turbo lint && pnpm turbo test && pnpm turbo build
```
runs ok!
---

feat: add experimental seal sdk

---

.changeset/fast-bees-matter.md
packages/bcs/src/bcs.ts
packages/bcs/tests/builder.test.ts
packages/docs/pages/bcs/index.mdx

[bcs] add bcs.byteVector

---

packages/walrus/examples/write-blob.ts
packages/walrus/src/client.ts
packages/walrus/src/types.ts
packages/walrus/src/wasm.ts

implement full write flow in walrus client

---

packages/walrus/examples/write-blob.ts
packages/walrus/src/client.ts
packages/walrus/src/types.ts

Extend and delete walrus blobs

---

packages/docs/content/typescript/executors.mdx
packages/docs/content/typescript/graphql.mdx
packages/docs/content/typescript/index.mdx
packages/docs/content/typescript/migrations/0.38.mdx
packages/docs/content/typescript/migrations/sui-1.0.mdx
packages/docs/content/typescript/plugins.mdx
packages/docs/content/zksend/link-builder.mdx

move 0.38 migration to separate doc

---

packages/walrus/examples/aggregator.ts
packages/walrus/examples/funded-keypiar.ts
packages/walrus/examples/publisher.ts
packages/walrus/examples/tsconfig.json
packages/walrus/examples/write-blob.ts
packages/walrus/package.json
packages/walrus/src/client.ts
packages/walrus/src/types.ts
pnpm-lock.yaml

Add publisher example

---

.changeset/violet-donkeys-wait.md
.github/workflows/turborepo.yml
packages/seal/package.json

fix(seal): rename ci, changeset

---

packages/docs/content/typescript/cryptography/_meta.json
packages/docs/content/typescript/cryptography/passkey.mdx

feat(doc): add section for passkey

---

.changeset/fifty-insects-trade.md
packages/seal/src/index.ts

fix(seal): export a type

---

.changeset/spicy-news-hide.md
packages/deepbook-v3/src/utils/constants.ts

Experimental Token for Deepbook
Constant change only

GIGA Token

---

.changeset/tasty-seals-perform.md
packages/suins/src/index.ts
packages/suins/src/suins-client.ts

Suins SDK Fix

---

packages/docs/content/dapp-kit/stashed.mdx
packages/docs/content/dapp-kit/wallet-provider.mdx
packages/docs/content/typescript/cryptography/passkey.mdx
packages/docs/content/typescript/zklogin.mdx
packages/docs/content/zksend/dapp.mdx
packages/docs/content/zksend/link-builder.mdx

Remove MDX references in links

---

packages/docs/app/llms.txt/route.ts
packages/docs/next.config.mjs
packages/docs/package.json
pnpm-lock.yaml

This should make the docs able to dump into LLMs without much work.
---

Add llms.txt to TS docs site

---

packages/walrus/examples/attributes/index.ts
packages/walrus/src/client.ts
packages/walrus/src/types.ts

walrus blob attributes

---

packages/walrus/examples/attributes/index.ts
packages/walrus/src/client.ts
packages/walrus/src/types.ts

[walrus] add methods for managing blob attributes

---

.changeset/nasty-rings-glow.md
packages/deepbook-v3/src/utils/constants.ts

Add SEND token to Deepbook V3 SDK
Constant change only, no test needed

SEND token

---

.changeset/brown-forks-jump.md
.changeset/silent-foxes-notice.md
packages/enoki/package.json
packages/enoki/src/EnokiFlow.ts
packages/typescript/package.json
packages/typescript/src/zklogin/address.ts
packages/typescript/src/zklogin/index.ts
packages/typescript/src/zklogin/jwt-decode.ts
packages/typescript/src/zklogin/jwt-utils.ts
packages/typescript/src/zklogin/nonce.ts
packages/typescript/src/zklogin/publickey.ts
packages/typescript/src/zklogin/utils.ts
pnpm-lock.yaml

Add check for malformed google iss in toZkLoginPublicIdentifier

---

.changeset/fluffy-chefs-hunt.md
packages/suins/package.json
pnpm-lock.yaml

Bump axios to 1.8.2 due to vulnerability
SDK works the same

Bump axios to 1.8.2 in suins

---

.changeset/dirty-pants-allow.md
packages/enoki/src/EnokiClient/type.ts
packages/enoki/src/EnokiKeypair.ts
packages/typescript/src/zklogin/publickey.ts

[enoki] update keypair and public key classes

---

packages/walrus/src/index.ts
packages/walrus/src/utils/bcs.ts

[walrus] add blotIdFromInt/toInt

---

.changeset/khaki-sloths-own.md
packages/kiosk/src/query/kiosk.ts
packages/kiosk/test/e2e/e2e.test.ts

[kiosks] Remove the use of MatchAny filters when loading owned kiosks

---

.changeset/flat-needles-jump.md
packages/graphql-transport/src/mappers/move.ts
packages/typescript/scripts/generate.ts
packages/typescript/src/client/types/generated.ts
packages/typescript/src/client/types/params.ts

update json rpc

---

packages/typescript/src/graphql/generated/latest/schema.graphql
packages/typescript/src/graphql/generated/latest/tada-env.ts

[graphql] update schemas

---

.changeset/hip-humans-tie.md
packages/docs/app/[[...slug]]/layout.tsx
packages/docs/content/walrus/index.mdx
packages/docs/content/walrus/meta.json
packages/walrus-wasm/package.json
packages/walrus/package.json

[walrus] enable publishing

---

.changeset/smart-cougars-buy.md
packages/enoki/src/EnokiClient/type.ts
packages/enoki/src/EnokiFlow.ts

enoki flow expose zkLogin public key

---

.changeset/blue-snakes-kick.md
packages/enoki/src/EnokiClient/type.ts

fix enoki build

---

.changeset/tricky-snails-sleep.md
packages/signers/package.json
packages/signers/src/webcrypto/index.ts

Add WebCrypto signer

---

.changeset/moody-zoos-arrive.md
packages/walrus/examples/tsconfig.json
packages/walrus/examples/write-from-wallet/index.tsx
packages/walrus/package.json
packages/walrus/src/client.ts
packages/walrus/src/types.ts
packages/walrus/src/utils/bcs.ts
pnpm-lock.yaml

[walrus] fix bcs parsing for testnet systemstate

---

.changeset/yellow-kids-mate.md
packages/signers/src/webcrypto/index.ts

Fix webcrypto signer

---

.changeset/honest-drinks-itch.md
.changeset/rare-fireants-argue.md
packages/docs/package.json
packages/enoki/package.json
packages/enoki/src/EnokiFlow.ts
packages/enoki/src/EnokiKeypair.ts
packages/enoki/src/react.tsx
packages/signers/src/webcrypto/index.ts
pnpm-lock.yaml

Adds experimental support to EnokiFlow 
---

Add experimental support for webcrypto signers in Enoki

---

packages/bcs/package.json
packages/create-dapp/package.json
packages/dapp-kit/package.json
packages/deepbook-v3/package.json
packages/deepbook/package.json
packages/enoki/package.json
packages/graphql-transport/package.json
packages/kiosk/package.json
packages/ledgerjs-hw-app-sui/package.json
packages/signers/package.json
packages/suins-toolkit/package.json
packages/suins/package.json
packages/typescript/package.json
packages/wallet-standard/package.json
packages/walrus/package.json
packages/zksend/package.json

turbo build for publish

---

.changeset/nice-stingrays-wink.md
packages/deepbook-v3/src/utils/constants.ts

WAL pools for Deepbook
Addresses verified

WAL pools for Deepbook

---

packages/docs/content/walrus/index.mdx
packages/walrus/README.md
packages/walrus/examples/funded-keypair.ts
packages/walrus/src/client.ts
packages/walrus/src/constants.ts
packages/walrus/src/types.ts
packages/walrus/src/utils/index.ts
packages/walrus/src/utils/memo.ts
packages/walrus/src/utils/object-loader.ts

update walrus SDK for mainnet

---

.changeset/curly-buses-crash.md
.changeset/sweet-trainers-camp.md
packages/typescript/src/transactions/plugins/utils.ts
packages/walrus/src/client.ts
packages/walrus/src/constants.ts
packages/walrus/src/contracts/subsidies.ts
packages/walrus/src/types.ts

[walrus] add support for subsideis

---

.github/workflows/seal-ci.yml

see title
execute workflow from branch
---

[ci] Creating a dispatch workflow for seal ci

---

packages/typescript/src/client/client.ts
packages/typescript/src/experimental/client.ts
packages/typescript/src/experimental/core.ts
packages/typescript/src/experimental/transports/jsonRPC.ts
packages/typescript/src/experimental/types.ts
packages/typescript/src/transactions/json-rpc-resolver.ts

Extends experimental client in SuiClient

---

packages/docs/content/typescript/cryptography/_meta.json
packages/docs/content/typescript/cryptography/webcrypto-signer.mdx

Webcrypto signer docs

---

.github/workflows/seal-ci.yml

PR for iterating on seal ci tests
manually execute the workflow
---

[ci] Get seal ci running

---

.changeset/dull-bugs-add.md
packages/seal/src/index.ts

[Seal] Expose errors, and update patch version (following the encryption format update)

---

.changeset/blue-flies-cheer.md
packages/walrus-wasm/package.json

add import to walrus-wasm exports

---

packages/seal/test/unit/integration.test.ts

[Seal] Increase test timeout for integration tests

---

.changeset/many-mice-listen.md

I forgot to add a changeset for the BCS library in https://github.com/MystenLabs/ts-sdks/pull/109 😅
n/a
---

Add changeset for the BCS package from previous Ledger PR

---

.changeset/full-facts-rescue.md
packages/docs/content/walrus/index.mdx
packages/walrus/.gitignore
packages/walrus/README.md
packages/walrus/examples/aggregator/index.ts
packages/walrus/examples/basics/attributes.ts
packages/walrus/examples/basics/delete-blob.ts
packages/walrus/examples/basics/read-blob.ts
packages/walrus/examples/funded-keypair.ts
packages/walrus/examples/publisher/index.ts
packages/walrus/examples/write-from-wallet/index.tsx
packages/walrus/src/client.ts

Update walrus docs and examples

---

.changeset/poor-pots-lick.md
packages/seal/README.md

chore: add readme

---

.changeset/quiet-pugs-report.md
packages/walrus/src/client.ts

[walrus] fix certifyBlob

---

packages/docs/content/seal/index.mdx
packages/docs/content/seal/meta.json

add doc for seal

---

packages/docs/content/walrus/index.mdx

Edit From should be **@mysten/walrus** and **writeBlob({ deletable: `false` })**

fix (docs: walrus): import package & writeBlob.option?

---

.changeset/late-planes-move.md
packages/walrus/examples/basics/delete-blob.ts
packages/walrus/src/client.ts
packages/walrus/src/index.ts

[related_issue](https://github.com/MystenLabs/ts-sdks/issues/181)

fix: delete blob tx with wrong pkg address

---

.changeset/bumpy-peas-clean.md
packages/docs/content/walrus/index.mdx
packages/walrus-wasm/package.json
packages/walrus/README.md
packages/walrus/src/client.ts
packages/walrus/src/types.ts
packages/walrus/src/wasm.ts
pnpm-lock.yaml

[walrus] add option to customize wasm url

---

.changeset/neat-crabs-train.md
packages/seal/src/session-key.ts

[Seal] Increase session key max TTL to 30

---

.changeset/cold-hats-help.md
packages/typescript/src/transactions/intents/CoinWithBalance.ts

Allow coinWithBalance return value to be used in multiple commands

---

.changeset/stale-insects-attack.md
packages/enoki/src/EnokiFlow.ts
packages/enoki/src/wallet/state.ts

Fixes https://github.com/MystenLabs/ts-sdks/issues/207.
- Manually tested signing works in the demo now

[enoki] fix the public key not being stored in IDB for the web crypto signer

---

.changeset/dark-cooks-jog.md
.changeset/fresh-nights-accept.md
packages/docs/content/walrus/index.mdx
packages/kiosk/src/tx/rules/resolve.ts
packages/kiosk/test/e2e/e2e.test.ts
packages/walrus/README.md
packages/walrus/src/storage-node/client.ts

[walrus/kiosk] fix kiosk bug and add onError to walrus options

---

.changeset/real-boats-shop.md
packages/kiosk/src/client/kiosk-client.ts

[kiosk] use default pagination limits

---

.changeset/shiny-needles-wait.md
packages/deepbook-v3/src/utils/constants.ts

New Package for Deepbook V3
https://suivision.xyz/txblock/CLnGztoLq1de8pQiYRpbhxxRjNM1oUUJwLnamFBMRiKE?tab=Changes

New Package for Deepbook V3

---

.changeset/orange-baboons-ask.md
packages/zksend/src/wallet/channel/events.ts
packages/zksend/src/wallet/channel/index.ts

[stashed] revert name to zksend channel name

---

.changeset/lucky-weeks-joke.md
packages/typescript/src/transactions/intents/CoinWithBalance.ts
packages/typescript/test/e2e/coin-with-balance.test.ts

Fix coinWithBalance with 0 balance from a gas coin

---

.changeset/cuddly-bees-deliver.md
packages/enoki-connect/.prettierignore
packages/enoki-connect/README.md
packages/enoki-connect/package.json
packages/enoki-connect/src/index.ts
packages/enoki-connect/src/wallet/index.ts
packages/enoki-connect/tsconfig.esm.json
packages/enoki-connect/tsconfig.json
packages/enoki-connect/typedoc.json
packages/enoki-connect/vitest.config.mts
pnpm-lock.yaml

Implements the wallet standard for EnokiConnect wallet
---

initialize enoki-connect wallet-standard

---

.changeset/cold-walls-bow.md
packages/slush-wallet/src/wallet/index.ts

stop setting transaction sender

---

packages/enoki-connect/package.json

use turbo for prepublishOnly build

---

packages/docs/content/dapp-kit/wallet-provider.mdx

Update link in docs

---

.changeset/new-grapes-develop.md
packages/seal/src/error.ts
packages/seal/test/unit/integration.test.ts

related: https://github.com/MystenLabs/seal/pull/85
InvalidPTB -> InvalidPTB "message"
---

fix: persist more verbose PTB error

---

.changeset/every-beers-remain.md
.changeset/seven-eels-visit.md
packages/seal/.prettierignore
packages/typescript/src/transactions/Commands.ts
packages/typescript/src/transactions/Transaction.ts
packages/typescript/src/transactions/TransactionData.ts
packages/typescript/src/transactions/intents/CoinWithBalance.ts
packages/typescript/test/unit/transactions/arguments.test.ts
packages/typescript/test/unit/transactions/async-thunks.test.ts
packages/typescript/test/unit/transactions/blob-registration.test.ts
packages/typescript/test/unit/transactions/object-inputs.test.ts
packages/typescript/test/unit/transactions/pure-serialization.test.ts
packages/typescript/test/unit/transactions/v1-json.test.ts
packages/walrus/src/client.ts

async thunk sections

---

.changeset/sour-taxes-grin.md
packages/typescript/src/transactions/Transaction.ts

memoize tx.add calls

---

packages/docs/content/walrus/index.mdx
packages/walrus/README.md

fix a typo

---

packages/docs/content/dapp-kit/slush.mdx
packages/docs/content/slush-wallet/dapp.mdx

Clarify docs

---

.changeset/young-sides-feel.md
packages/typescript/src/client/client.ts
packages/typescript/src/experimental/core.ts
packages/typescript/src/experimental/transports/graphql.ts
packages/typescript/src/experimental/transports/jsonRPC.ts
packages/typescript/src/experimental/types.ts
packages/typescript/src/graphql/generated/queries.ts
packages/typescript/src/graphql/queries/verifyZkLoginSignature.graphql
packages/typescript/src/multisig/publickey.ts
packages/typescript/src/verify/verify.ts
packages/typescript/src/zklogin/publickey.ts
packages/typescript/test/e2e/verify-signatures.test.ts

Add support for json rpc client when verifying zklogin signatures

---

packages/zksend/src/links/claim.ts

update api url

---

packages/seal/package.json
packages/seal/src/error.ts
packages/seal/src/key-server.ts
packages/seal/src/keys.ts
packages/seal/src/utils.ts
packages/seal/test/unit/key-server.test.ts
pnpm-lock.yaml

Add a minimal key server version, and compare with the version from the response header.
Unit tests.
---

Check key server version

---

packages/seal/src/error.ts
packages/seal/test/unit/key-server.test.ts
pnpm-lock.yaml

Add new errors from version alignment between sdk and server.
Also reverts an accidental change to pnpm-lock.yaml from https://github.com/MystenLabs/seal/pull/92.
N/A
---

Align with errors from Seal key server

---

.changeset/pretty-foxes-flash.md
packages/bcs/src/reader.ts
packages/bcs/tests/bcs.test.ts

Correctly handle byteOffset in Uint8Arrays when reading bcs bytes

---

packages/docs/package.json
packages/docs/typedoc.json
pnpm-lock.yaml

add enoki-connect to docs

---

.changeset/fine-goats-relax.md
packages/enoki-connect/src/index.ts
packages/enoki-connect/src/wallet/index.ts

allow registering multiple enoki-connect wallets
- removes `registerEnokiConnectWallet`
- adds `registerEnokiConnectWallets`
---

registerEnokiConnectWallets

---

.changeset/cold-zoos-move.md
packages/zksend/src/links/claim.ts
packages/zksend/src/links/get-sent-transactions.ts

Remove object and balance changes

---

packages/seal/src/bls12381.ts
packages/seal/src/dem.ts
packages/seal/src/encrypt.ts
packages/seal/src/ibe.ts
packages/seal/src/kdf.ts
packages/seal/src/utils.ts

Add missing docs, comments and clarifications in the seal sdk code.
N/A
---

[seal] Various clean ups and clarifications

---

.changeset/good-poets-reply.md
packages/enoki-connect/demo-dapp/src/Actions.tsx
packages/enoki-connect/src/wallet/index.ts

update metadata api

---

.changeset/tame-walls-dig.md
packages/enoki-connect/src/wallet/index.ts

[enoki-connect] add devnet to supported networks

---

.changeset/rude-carpets-like.md
packages/seal/src/index.ts

chore: export the object type for SessionKey

---

.changeset/giant-vans-poke.md
packages/deepbook-v3/src/transactions/deepbookAdmin.ts

Allow admin to update tick size
Tested on testnet

Allow admin to update tick size

---

packages/seal/src/client.ts
packages/seal/src/decrypt.ts
packages/seal/src/dem.ts
packages/seal/src/elgamal.ts
packages/seal/src/encrypt.ts
packages/seal/src/error.ts
packages/seal/src/key-server.ts
packages/seal/src/keys.ts
packages/seal/src/utils.ts

Cleaning up seal codebase. Simplifies some flows in the client, but there should be no functional changes.
N/A
---

[seal] Clean ups and simplifications

---

.changeset/curly-birds-walk.md
packages/deepbook-v3/src/transactions/deepbookAdmin.ts

Function to adjust min/lot size as admin
Tested on testnet

Adjust min/lot size as admin (Deepbook SDK)

---

.changeset/olive-badgers-happen.md
packages/window-wallet-core/src/jwt-session/index.ts
packages/window-wallet-core/src/web-wallet-channel/wallet-post-message-channel.ts

* remove opener origin check as it's not possible to access it
* add extra CryptoKey type to verifyJwtSession secretKey
---

improve verifyJwtSession

---

.changeset/plain-doodles-shout.md
packages/window-wallet-core/src/web-wallet-channel/wallet-post-message-channel.ts

* left over from previews PR #299 
---

verifyJwtSession remove opener check

---

.changeset/free-hotels-rest.md
.changeset/vast-bushes-enter.md
packages/dapp-kit-next/src/core/actions/index.ts
packages/dapp-kit-next/src/core/index.ts
packages/dapp-kit-next/src/current-account-signer.ts
packages/typescript/src/cryptography/keypair.ts
packages/typescript/src/verify/verify.ts
packages/typescript/src/zklogin/publickey.ts
packages/walrus/src/client.ts

Add wallet-signer

---

.changeset/clean-symbols-wonder.md
.changeset/free-hotels-rest.md
.changeset/vast-bushes-enter.md
.changeset/wide-heads-own.md
.changeset/wise-papayas-yell.md
packages/dapp-kit-next/src/core/actions/signer.ts
packages/dapp-kit-next/src/core/index.ts
packages/dapp-kit-next/src/current-account-signer.ts
packages/docs/content/typescript/install.mdx
packages/typescript/src/cryptography/keypair.ts
packages/typescript/src/experimental/core.ts
packages/typescript/src/experimental/index.ts
packages/typescript/src/experimental/transports/graphql.ts
packages/typescript/src/experimental/transports/json-rpc-resolver.ts
packages/typescript/src/experimental/transports/jsonRPC.ts
packages/typescript/src/experimental/transports/utils.ts
packages/typescript/src/experimental/types.ts
packages/typescript/src/graphql/generated/queries.ts
packages/typescript/src/graphql/queries/transactions.graphql
packages/typescript/src/transactions/ObjectCache.ts
packages/typescript/src/transactions/Transaction.ts
packages/typescript/src/transactions/executor/caching.ts
packages/typescript/src/transactions/index.ts
packages/typescript/src/transactions/intents/CoinWithBalance.ts
packages/typescript/src/transactions/plugins/NamedPackagesPlugin.ts
packages/typescript/src/transactions/resolve.ts
packages/typescript/src/verify/verify.ts
packages/typescript/src/zklogin/publickey.ts
packages/typescript/test/unit/transactions/async-thunks.test.ts
packages/walrus/src/client.ts

Add signAndExecute to Signer and use core API for transaction resolution

---

.changeset/clear-rings-obey.md
packages/walrus/src/client.ts

[walrus] fix subsidies contract id after upgrade

---

.changeset/gold-bags-beg.md
packages/docs/content/typescript/cryptography/keypairs.mdx
packages/typescript/src/cryptography/keypair.ts

update docs on parsing bech32 keypairs

---

.changeset/fast-beers-grab.md
packages/deepbook-v3/src/transactions/deepbookAdmin.ts

Deepbook float rounding error temporary fix
Tested on testnet

Deepbook float temp fix

---

.changeset/some-sheep-shake.md
packages/deepbook-v3/src/utils/constants.ts

XBTC/USDC Pool added
Constant update only

XBTC/USDC Pool

---

packages/codegen/.prettierignore
packages/codegen/package.json
packages/codegen/src/bin/bash-complete.ts
packages/codegen/src/bin/cli.ts
packages/codegen/src/cli/cli.ts
packages/codegen/src/cli/commands/generate/command.ts
packages/codegen/src/cli/commands/generate/impl.ts
packages/codegen/src/cli/context.ts
packages/codegen/src/index.ts
packages/codegen/src/move-module-builder.ts
packages/codegen/tsconfig.esm.json
packages/codegen/tsconfig.json
pnpm-lock.yaml

Command to re-generate the test files:
```
pnpm tsx src/bin/cli.ts generate -o tests/generated tests/move/subsidies tests/move/wal tests/move/wal_exchange tests/move/walrus && pnpm lint:fix
```
---

codegen cli

---

packages/enoki-connect/demo-dapp/src/Actions.tsx

enoki-connect demo app fix verify

---

packages/enoki-connect/demo-dapp/package.json
packages/enoki-connect/demo-dapp/src/Actions.tsx
pnpm-lock.yaml

add transaction actions

---

.github/workflows/e2e.yml

disable graphql-transport tests

---

packages/seal/src/bls12381.ts
packages/seal/src/decrypt.ts
packages/seal/src/ibe.ts

Add nonce check needed for CCA security.
Unit tests.
---

[seal] Add nonce check

---

.changeset/tame-meals-pay.md
packages/typescript/src/transactions/Transaction.ts
packages/typescript/test/unit/transactions/async-thunks.test.ts

update thunk results after building

---

.changeset/floppy-spies-relax.md
.changeset/shiny-deer-own.md
.changeset/tame-pigs-watch.md
packages/seal/src/client.ts
packages/seal/src/session-key.ts
packages/seal/src/types.ts
packages/seal/test/unit/integration.test.ts
packages/seal/test/unit/session-key.test.ts
packages/typescript/src/experimental/transports/graphql.ts

check if the package is first version. 
---

fix(seal): check package ID version = 1

---

packages/sui-grpc/src/core.ts

[grpc] defer rejection of bcs contents on core object methods

---

packages/seal/src/session-key.ts

Add MVR name as parameter to SessionKey create method.
Uunit tests.
---

[seal] Add MVR name as parameter to SessionKey create method

---

packages/codegen/package.json
packages/move-bytecode-template/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

[codegen] enable publishing

---

.changeset/plenty-pandas-unite.md
packages/codegen/package.json
packages/codegen/src/cli/commands/generate/command.ts
packages/codegen/src/cli/commands/generate/impl.ts
packages/codegen/src/config.ts
packages/codegen/src/index.ts
packages/codegen/src/utils.ts
packages/codegen/sui-codegen.config.ts
pnpm-lock.yaml

[codegen] add config files

---

.changeset/wide-apples-help.md
packages/codegen/src/generate-utils.ts
packages/codegen/tests/generated/utils/index.ts
packages/suins-v2/src/contracts/utils/index.ts
packages/walrus/package.json
packages/walrus/src/client.ts
packages/walrus/src/contracts/subsidies/subsidies.ts
packages/walrus/src/contracts/utils/index.ts
packages/walrus/src/contracts/wal/wal.ts
packages/walrus/src/contracts/wal_exchange/wal_exchange.ts
packages/walrus/src/contracts/walrus/apportionment_queue.ts
packages/walrus/src/contracts/walrus/auth.ts
packages/walrus/src/contracts/walrus/blob.ts
packages/walrus/src/contracts/walrus/committee.ts
packages/walrus/src/contracts/walrus/encoding.ts
packages/walrus/src/contracts/walrus/extended_field.ts
packages/walrus/src/contracts/walrus/init.ts
packages/walrus/src/contracts/walrus/metadata.ts
packages/walrus/src/contracts/walrus/node_metadata.ts
packages/walrus/src/contracts/walrus/shared_blob.ts
packages/walrus/src/contracts/walrus/staked_wal.ts
packages/walrus/src/contracts/walrus/staking.ts
packages/walrus/src/contracts/walrus/storage_accounting.ts
packages/walrus/src/contracts/walrus/storage_node.ts
packages/walrus/src/contracts/walrus/storage_resource.ts
packages/walrus/src/contracts/walrus/system.ts
packages/walrus/src/contracts/walrus/upgrade.ts
packages/walrus/sui-codegen.config.ts

walrus codegen no init

---

.changeset/smart-symbols-hide.md
packages/typescript/src/experimental/client.ts
packages/typescript/src/experimental/core.ts
packages/typescript/src/experimental/types.ts

Add default mvr urls

---

.changeset/quiet-rules-marry.md
packages/walrus/src/client.ts
packages/walrus/src/fan-out-proxy/client.ts
packages/walrus/src/types.ts
packages/walrus/src/utils/quilts.ts

[walrus] update linear tip config

---

.changeset/true-walls-smoke.md
packages/docs/content/walrus/index.mdx
packages/walrus/README.md
packages/walrus/examples/upload-relay/write-blob.ts
packages/walrus/src/client.ts
packages/walrus/src/types.ts
packages/walrus/src/upload-relay/client.ts

[walrus] rename fanout proxy to upload relay

---

packages/docs/content/typescript/cryptography/multisig.mdx
packages/docs/content/typescript/cryptography/passkey.mdx

fix: multisig doc and passkey

---

packages/seal/src/client.ts
packages/seal/src/index.ts
packages/seal/src/types.ts

export interfaces for client method options

---

packages/seal/src/bls12381.ts
packages/seal/src/decrypt.ts
packages/seal/src/dem.ts
packages/seal/src/encrypt.ts
packages/seal/src/kdf.ts
packages/seal/src/utils.ts
packages/seal/test/unit/encrypt.test.ts

[Seal] Small improvements

---

.changeset/empty-camels-send.md
packages/docs/content/walrus/index.mdx
packages/walrus/README.md
packages/walrus/examples/quilt/write-flow.ts
packages/walrus/examples/write-from-wallet/upload.tsx
packages/walrus/src/client.ts
packages/walrus/src/types.ts

[walrus] move epochs, owner, and deletable options to flow.register

---

.changeset/tidy-gifts-cut.md
packages/typescript/src/experimental/transports/json-rpc-resolver.ts
packages/typescript/test/e2e/object-display-standard.test.ts
packages/typescript/test/e2e/party-objects.test.ts
packages/typescript/test/e2e/utils/globalSetup.ts

add test for party object transfer

---

.changeset/fancy-parrots-wish.md
packages/enoki-connect/demo-dapp/src/main.tsx
packages/enoki-connect/src/wallet/index.ts

[enoki-connect] add docs for registerEnokiConnectWallets method

---

.changeset/cyan-foxes-run.md
packages/deepbook-v3/src/utils/constants.ts

Add IKA pool
No testing needed, constant update only

Add IKA pool

---

.changeset/cute-brooms-knock.md
packages/walrus/src/upload-relay/client.ts

fix parsing of linear tip config

---

packages/seal/src/shamir.ts

There can be at most 255 shares in total -- one per non-zero element of GF256.
Unit test.
---

[seal] Fix input check

---

packages/seal/src/decrypt.ts
packages/seal/src/ibe.ts

Better naming for checking share consistency.
Unit tests.
---

[seal] Better naming

---

.changeset/legal-pens-sink.md
.changeset/shiny-icons-sip.md
packages/move-bytecode-template/README.md
packages/move-bytecode-template/package.json
packages/walrus-wasm/package.json

fix exports for wasm packages

---

.changeset/seven-bugs-wink.md
packages/typescript/scripts/update-graphql-schemas.ts
packages/typescript/src/client/index.ts
packages/typescript/src/client/types/index.ts
packages/typescript/src/graphql/schemas/2024.1/index.ts
packages/typescript/src/graphql/schemas/2024.4/index.ts
packages/typescript/src/graphql/schemas/latest/index.ts

Fix type-only exports

---

.changeset/free-tips-carry.md
packages/seal/src/index.ts
packages/seal/src/key-server.ts
packages/seal/test/unit/integration.test.ts
packages/seal/test/unit/key-server.test.ts

see seal docs for any available key servers in testnet and mainnet: https://github.com/MystenLabs/seal/blob/main/Pricing.md#seal-pricing
---

[seal]: remove getAllowlistedKeyServers

---

.changeset/slow-bats-punch.md
packages/typescript/src/transactions/executor/parallel.ts
packages/typescript/test/e2e/parallel-executor.test.ts
packages/zksend/src/index.test.ts
packages/zksend/src/links/claim.ts

Fix remaining balance check in ParallelExecutor

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/validate-ai-assistance.yml

Copying the internal AI assistance notice template. The PR workflow was generated via AI.
---

AI Assistance Notice

---

.changeset/public-beers-return.md
packages/seal/test/unit/encrypt.test.ts
packages/seal/test/unit/integration.test.ts

[seal] increase timeout for tests

---

.github/workflows/turborepo.yml
packages/seal/test/unit/key-server.test.ts

[seal] reenable test

---

packages/seal/README.md

[seal] update readme

---

packages/seal/README.md

fix linting

---

.changeset/every-sides-clap.md
.changeset/large-tires-lose.md
packages/docs/content/walrus/index.mdx
packages/typescript/src/experimental/transports/json-rpc-resolver.ts
packages/typescript/src/transactions/data/internal.ts
packages/typescript/src/transactions/data/v2.ts
packages/typescript/src/transactions/object.ts
packages/typescript/test/unit/transactions/arguments.test.ts
packages/typescript/test/unit/transactions/object-inputs.test.ts
packages/typescript/test/unit/transactions/system-objects.test.ts
packages/wallet-standard/src/types.ts

[sui] Fix tx.object.random() and tx.object.denyList()

---

.changeset/tidy-ghosts-start.md
packages/walrus/examples/funded-keypair.ts
packages/walrus/src/utils/quilts.ts

[walrus] fix bug that caused quilts with large indexes to be invalid

---

.changeset/empty-bats-wish.md
packages/codegen/src/cli/commands/generate/impl.ts
packages/codegen/src/config.ts
packages/codegen/src/index.ts
packages/codegen/src/move-module-builder.ts
packages/codegen/tests/generated/subsidies/subsidies.ts
packages/suins-v2/src/contracts/suins/admin.ts
packages/suins-v2/src/contracts/suins/auction.ts
packages/suins-v2/src/contracts/suins/controller.ts
packages/suins-v2/src/contracts/suins/name_record.ts
packages/suins-v2/src/contracts/suins/payment.ts
packages/suins-v2/src/contracts/suins/registry.ts
packages/suins-v2/src/contracts/suins/suins_registration.ts
packages/suins-v2/src/contracts/suins_coupons/coupon_house.ts
packages/suins-v2/src/contracts/suins_coupons/rules.ts
packages/suins-v2/src/contracts/suins_payments/payments.ts
packages/suins-v2/src/contracts/suins_temp_subdomain_proxy/subdomain_proxy.ts
packages/suins-v2/src/contracts/utils/index.ts
packages/walrus/src/contracts/utils/index.ts
packages/walrus/src/contracts/walrus/init.ts
packages/walrus/src/contracts/walrus/staking.ts
pnpm-lock.yaml

[codegen] add option to codegen private functions

---

.changeset/thick-mails-marry.md
packages/seal/src/index.ts

[seal] export DemType

---

.changeset/heavy-loops-hunt.md
.changeset/seven-boats-teach.md
packages/sui-grpc/src/core.ts
packages/typescript/src/experimental/core.ts
packages/typescript/src/experimental/mvr.ts
packages/typescript/src/experimental/transports/graphql.ts

improve mvr support

---

packages/payment-kit/src/client.ts
packages/payment-kit/src/index.ts
packages/payment-kit/src/types.ts

[Payment Kit] Added `asClientExtension`
