MystenLabs/ts-sdks

- .changeset/mean-kiwis-argue.md
- packages/typescript/src/keypairs/passkey/keypair.ts
- packages/typescript/test/unit/cryptography/passkey.test.ts
review context: https://github.com/MystenLabs/sui/pull/20722
---
> feat: add recover option to sdk

- packages/walrus/src/storage-node/client.ts
- packages/walrus/src/storage-node/types.ts
We need the `getBlobStatus` method for retrieving information about the certification epoch of a blob which is needed to determine which committee to read blobs from during epoch changes. I transformed the API response at the client level because it's annoying to work with a union of nested objects vs having a discriminated union
See: https://github.com/MystenLabs/ts-sdks/pull/67
- Lewks good locally
> [walrus] add getBlobStatus to the storage node API client

- packages/walrus/src/client.ts
- packages/walrus/src/types.ts
- packages/walrus/src/utils/index.ts
- packages/walrus/src/utils/randomness.ts
Storage nodes don't always contain the metadata for a blob, so this PR implements the same strategy the Rust client uses for metadata reads – we randomize the committee, try to fetch metadata from the first node and return if successful, otherwise start fetching in parallel until we get a successful response or reach quorum on the blob being blocked/not certified.
- Tested with reading a bunch of blobs
---
> [walrus] make blob metadata fetches more robust

- packages/walrus/src/client.ts
- packages/walrus/src/types.ts
- packages/walrus/src/utils/randomness.ts
This PR makes the sliver fetching more robust, specifically:
- We want to try to fetch slivers from nodes at random proportional to how many shards they possess
- If we fail fetching from a given node, we skip subsequent requests to that node
- If we hit too many 404/451 errors, we bail out if quorum was reached
- If we hit so many errors so that we can't fetch `minSymbols`, we bail out
I'm out all this week on PTO, so just getting this up and if there's a more preferred way to go about the async control flow management here please be my guest! I just used a simple chunking approach where we execute against the chunked sliver indices in column-wise order so that we preserve the weighted random ordering (felt kinda meh about this but it works). 
---
- Tested reads on a bunch of blobs
> [walrus][out on PTO - plz take over] make sliver reads more robust

- .changeset/fluffy-students-mix.md
- packages/signers/src/webcrypto/index.ts
The chain needs `lowS`, but web crypto doesn't enforce this, so we need to normalize it. 
---
> Fix signatures for WebCrypto signer

- .changeset/curvy-beans-complain.md
- .changeset/four-lobsters-promise.md
- .changeset/ninety-moles-raise.md
- packages/dapp-kit/src/hooks/wallet/useSignAndExecuteTransaction.ts
- packages/dapp-kit/src/hooks/wallet/useSignPersonalMessage.ts
- packages/dapp-kit/src/hooks/wallet/useSignTransaction.ts
- packages/dapp-kit/src/hooks/wallet/useUnsafeBurnerWallet.ts
- packages/dapp-kit/test/hooks/useSignAndExecuteTransaction.test.tsx
- packages/dapp-kit/test/hooks/useSignPersonalMessage.test.tsx
- packages/dapp-kit/test/hooks/useSignTransaction.test.tsx
- packages/dapp-kit/test/mocks/mockFeatures.ts
- packages/docs/content/dapp-kit/wallet-hooks/useSignAndExecuteTransaction.mdx
- packages/docs/content/dapp-kit/wallet-hooks/useSignPersonalMessage.mdx
- packages/docs/content/dapp-kit/wallet-hooks/useSignTransaction.mdx
- packages/wallet-standard/src/chains.ts
- packages/wallet-standard/src/features/suiSignPersonalMessage.ts
- packages/zksend/src/wallet/index.ts
Message signing for zkLogin accounts technically depends on a `chain`/`network` because proofs are network-bound. While I'm at it, I'm also going to tweak the default `chain` behavior when interacting with wallets from dapp-kit so that the active network of the dApp is used during signing by default.
- Existing test coverage + new tests
- Manual testing with a dApp
> [dapp-kit / wallet-standard] let signPersonalMessage take a chain parameter and default the signing chain to the active network

- .changeset/metal-steaks-grab.md
- packages/typescript/src/transactions/plugins/NamedPackagesPlugin.ts
- packages/typescript/src/transactions/plugins/utils.ts
- packages/typescript/src/utils/sui-types.ts
- packages/typescript/test/e2e/named-packages-plugin.test.ts
- packages/typescript/test/unit/types/common.test.ts
This PR:
1. Rewrites the plugin to use the new MVR API endpoints
2. Enables composite type resolution, so that it can work with the "static" generation tool
3. Adds e2e testing using a pretty complex package (multi-versions, cross-chain).
Added new e2e tests.
regarding backwards compatibility (breaking): the GQL endpoints won't really be usable anymore. We are still in an experimental state.
> [mvr-plugin] Rewrite plugin to use the new API

- packages/seal/src/decrypt.ts
- packages/seal/src/ibe.ts
- packages/seal/src/kdf.ts
- packages/seal/test/unit/encrypt.test.ts
Update the IBE in Seal to include all public parameters in the hash, aligning the implementation with that of "Identity Based Encryption Without Redundancy" by Libert and Quisquater.
Unit tests.
---
> Include all public values in hash

- packages/build-scripts/package.json
- packages/build-scripts/src/build-dapp-kit-next.ts
- packages/dapp-kit-next/LICENSE
- packages/dapp-kit-next/README.md
- packages/dapp-kit-next/package.json
- packages/dapp-kit-next/src/components/dapp-kit-connect-modal.svelte
- packages/dapp-kit-next/src/components/internal/wallet-list.svelte
- packages/dapp-kit-next/src/index.ts
- packages/dapp-kit-next/svelte.config.js
- packages/dapp-kit-next/tsconfig.esm.json
- packages/dapp-kit-next/tsconfig.json
- packages/dapp-kit-next/tsconfig.svelte.json
- pnpm-lock.yaml
This PR scaffolds out thew new version of dapp-kit using Svelte for shipping framework agnostic web components.
- I'll add examples to the library in follow-up PRs, I didn't want to do that here to keep the PR more reviewable
- Tested the components in a React + Vite app and in a plain old HTML file
- The `WalletList` component stays internal (i.e., not defined as a web component)
React rendering:
Normal HTML:
> [dapp-kit-next] scaffold out new library with rendering of web components

- .changeset/little-spoons-bet.md
- packages/create-dapp/templates/react-e2e-counter/README.md
- packages/docs/content/typescript/index.mdx
- packages/typescript/README.md
- packages/typescript/src/faucet/faucet.ts
- packages/typescript/src/faucet/index.ts
The faucet will use the new `/v2/gas` routes very soon. This PR updates it in a few places, but ideally I would need @hayes-mysten to have a look to make sure we're covering it everywhere.
Please note that both `/gas` and `/v1/gas` will be deprecated, and an error response will be returned to use `/v2/gas` instead (which is heavily rate limited). Also, the response has changed. See https://github.com/MystenLabs/sui/issues/21775
!!! Not sure how the CI picks up changes from main `sui` repo, but probably this PR: https://github.com/MystenLabs/sui/pull/21865 needs to be merged there first.
---
> [DO NOT MERGE YET][faucet] Update faucet routes

- packages/deepbook/test/e2e/globalSetup.ts
- packages/deepbook/test/e2e/setup.ts
- packages/docs/content/typescript/faucet.mdx
- packages/graphql-transport/src/methods.ts
- packages/graphql-transport/test/globalSetup.ts
- packages/kiosk/test/e2e/globalSetup.ts
- packages/kiosk/test/e2e/setup.ts
- packages/suins/test/toolbox.ts
- packages/typescript/README.md
- packages/typescript/src/faucet/faucet.ts
- packages/typescript/test/e2e/utils/globalSetup.ts
- packages/typescript/test/e2e/utils/setup.ts
- packages/walrus/examples/funded-keypair.ts
- packages/zksend/src/index.test.ts
This PR updates the test suite to use the latest faucet v2. This new version includes a simplified local faucet which now uses `/v2/gas` as the standard route.
Before this can be merged/used, we need to also update the `sui-tools` image to refer to a commit that has the new local faucet changes in the main `sui-repo`.
---
> [faucet] Move to the latest faucet v2

- .changeset/wicked-teams-read.md
- packages/seal/src/session-key.ts
- packages/seal/test/unit/integration.test.ts
- packages/seal/test/unit/session-key.test.ts
add feat to import and export session key, useful to persist in web storage e.g. indexed db
unit test
---
> feat(seal): add import and export session key

- .changeset/many-ads-drum.md
- packages/signers/README.md
- packages/signers/src/ledger/index.ts
Fixes https://github.com/MystenLabs/ts-sdks/issues/262. I forgot to serialize the messsage bytes to BCS :oops:
```
williamrobertson@Williams-MacBook-Pro signers % pnpm tsx src/ledger/test.ts
sig AIWgztm+twdZws6yxn+p9NBNn5aFa0lz5YBvUHIR/iaWI6Q98h7zTCjVqIpjGZE7ibnAi1HpU5kt+GReLrUdjwCFQ+ltaeiDqXcXeTh0s9p1SPNI5+eQfiUKGMOqORWGMA==
parsed address 0x1255d09304c5cc824b9ef4fd9196f5b8e96167b4fb0266f70dd36829ad519d5d
verified address 0x1255d09304c5cc824b9ef4fd9196f5b8e96167b4fb0266f70dd36829ad519d5d
```
> [signers] fix broken message signing in the Ledger signer

- .changeset/floppy-bobcats-stop.md
- packages/wallet-standard/src/detect.ts
- packages/wallet-standard/src/features/suiReportTransactionEffects.ts
- packages/wallet-standard/src/features/suiSignAndExecuteTransaction.ts
- packages/wallet-standard/src/features/suiSignAndExecuteTransactionBlock.ts
- packages/wallet-standard/src/features/suiSignMessage.ts
- packages/wallet-standard/src/features/suiSignPersonalMessage.ts
- packages/wallet-standard/src/features/suiSignTransaction.ts
- packages/wallet-standard/src/features/suiSignTransactionBlock.ts
This is a super tiny PR to expose the names of features so you can just use variables in wallet implementations and libraries which matches what the core standard exposes.
- CI
- 👁️
> [wallet-standard] expose feature name variables

- .changeset/blue-mangos-float.md
- packages/seal/src/client.ts
- packages/seal/src/error.ts
- packages/seal/test/unit/integration.test.ts
Handle weighted/repeated key servers better in the client. Currently, fetch is called multiple times per key server because the `Set<KeyServer>` does not enforce uniqueness since `KeyServer` is a custom object.
Unit tests.
---
> [seal] Fix handling of weighted key servers

- .changeset/rare-cougars-chew.md
- packages/walrus/examples/basics/read-blob.ts
- packages/walrus/src/client.ts
- packages/walrus/src/types.ts
To compute the metadata for a blob before uploading it, you have to call `encodeBlob` which does a lot of other stuff and is really meant to be used during the write flow. This PR exposes a `computeBlobMetadata` method on the client which is about 2x faster (3s -> 1.5s) than `encodeBlob` given the fact that you don't have to make any network requests.
The real perf slowdown is with the WASM bindings so this doesn't totally fix the reported issue in https://github.com/MystenLabs/walrus/issues/2030, but eh it might still be worth shipping anyway. LMK what you think when you're back from PTO @hayes-mysten 
- Tested manually
> [walrus] add `computeBlobMetadata` method to the client

- packages/docs/content/typescript/hello-sui.mdx
Function requestSuiFromFaucetV1 has been deprecated in https://github.com/MystenLabs/ts-sdks/pull/214 but hello-sui.mdx still use it.
This PR is for updating this. And would it be better to keep only one requestSuiFromFaucet function to prevent other versions like requestSuiFromFaucetV3 or requestSuiFromFaucetV4 from appearing?
> docs: update request SUI from faucet section in hello-sui.mdx 

- packages/dapp-kit-next/src/core/initializers/sync-state-to-storage.ts
- packages/dapp-kit-next/src/index.ts
- packages/dapp-kit-next/src/utils/wallets.ts
The auto-connection functionality for Slush Web wasn't working because `getWalletUniqueIdentifier` was returning the `name` instead of the `id` for `UiWallets` since I had a busted conditional check on the wallet symbol (which you obviously can't do lol). This PR fixes that issue by just requiring a handle (wallet account or wallet) to be passed in, since that is what external consumers will be working with on the UI side.
> [dapp-kit-next] fix bad type narrowing check returning the wrong wallet ID

- .changeset/lemon-rice-cover.md
- packages/slush-wallet/src/wallet/index.ts
Wallet standard wallets should hydrate their previously authorized accounts in the constructor without requiring a call to `connect` (the `silent` flag will be deprecated eventually JFYI).
- Tested that auto-connecting works with the new and old versions of dApp Kit
> [slush-wallet] authorize previously saved accounts without requiring a call to `connect`

- packages/dapp-kit-next/src/core/actions/sign-and-execute-transaction.ts
- packages/dapp-kit-next/src/core/actions/sign-transaction.ts
- packages/dapp-kit-next/src/core/index.ts
- packages/dapp-kit-next/src/core/store.ts
- packages/dapp-kit-next/src/core/types.ts
- packages/dapp-kit-next/src/index.ts
- packages/dapp-kit-next/src/utils/networks.ts
This PR changes the client type from the base client to the core client with an optional method for resolving SuiNS names (this is used in the connected account dropdown / button for the pre-built UI components).
> [dapp-kit-next] fix client typings for optional SuiNS name resolution in the components

- .changeset/true-queens-rule.md
- packages/enoki/src/wallet/utils.ts
Eh I realized as soon as I landed https://github.com/MystenLabs/ts-sdks/pull/382/files#r2153182218 that I made `getWalletMetadata` return null instead of throw originally so you could use `isGoogleWallet` XX type methods directly (am working on getting docs ready for this)
Before this would throw, now it works as expected:
```
const wallets = useWallets();
const googleWallet = wallets.find(isGoogleWallet);
```
- Manual testing
> [enoki] revert small change that made `getWalletMetadata` throw an error

- packages/dapp-kit-next/packages/dapp-kit-core/src/core/actions/sign-and-execute-transaction.ts
- packages/dapp-kit-next/packages/dapp-kit-core/src/core/actions/sign-transaction.ts
- packages/dapp-kit-next/packages/dapp-kit-core/src/core/store.ts
- packages/dapp-kit-next/packages/dapp-kit-core/src/utils/wallets.ts
- packages/dapp-kit-next/packages/dapp-kit-core/src/wallets/index.ts
This PR adds backward compatibility for old signing/executing features just to save a little headache down the road (came around on this) 😛 
- Testing with burner wallet
> [dapp-kit-next] add backwards compatibility for old signing/executing features

- .changeset/real-wolves-hide.md
- packages/codegen/package.json
- packages/codegen/src/generate-utils.ts
- packages/codegen/tests/generated/utils/index.ts
- packages/codegen/tests/utils.test.ts
- packages/mvr-static/tests/parsing.test.ts
- packages/suins-v2/src/contracts/utils/index.ts
- packages/walrus/src/contracts/utils/index.ts
Small fix for the codegen's `normalizeMoveArguments` util to fix args' resolution, when a Sui std arg object is present (i.e. `Clock`, `Random`, `DenyList` or `SuiSystemState`).
Previously, the function would not move on to the next argType after pushing the correct value into the `normalizedArgs` array for that Sui type, but would continue the iteration, trying to process the arg as if it were an arbitrary arg, which would eventually result in errors like "Parameter clock is required".
- Added test cases
- ensured they were failing for the previous code, indicating the issue
- added the fix
- made sure the tests were passing after.
> fix(codegen): move to next arg when resolved sui std arg in `normalizeMoveArguments`

- packages/dapp-kit-next/examples/next-js/simple/README.md
- packages/dapp-kit-next/examples/next-js/simple/app/ClientOnlyConnectButton.tsx
- packages/dapp-kit-next/examples/next-js/simple/app/dApp-kit.ts
- packages/dapp-kit-next/examples/next-js/simple/app/globals.css
- packages/dapp-kit-next/examples/next-js/simple/app/layout.tsx
- packages/dapp-kit-next/examples/next-js/simple/app/page.tsx
- packages/dapp-kit-next/examples/next-js/simple/eslint.config.mjs
- packages/dapp-kit-next/examples/next-js/simple/next.config.ts
- packages/dapp-kit-next/examples/next-js/simple/package.json
- packages/dapp-kit-next/examples/next-js/simple/tsconfig.json
- pnpm-lock.yaml
Added Next.js example for `dapp-kit-next` -- it requires client-side rendering for the components. Used `npx create-next-app@latest` to create the project.
- ran the example and played around with the button
---
> Next.js example for dapp-kit-next

- .changeset/gold-cooks-pay.md
- packages/codegen/src/generate-utils.ts
- packages/codegen/src/move-module-builder.ts
- packages/codegen/tests/generated/utils/index.ts
- packages/codegen/tests/generated/walrus/init.ts
- packages/codegen/tests/generated/walrus/staking.ts
- packages/codegen/tests/utils.test.ts
- packages/deepbook-v3/src/contracts/utils/index.ts
- packages/suins-v2/src/contracts/utils/index.ts
- packages/walrus/src/contracts/utils/index.ts
Skip system args in codegen's arg names list.
Added the missing test for args as `object` WITH trailing arg after the system one (we had 'object & no trailing', 'array & trailing' and 'array & no trailing' before ._. )
---
> fix(codegen): skip system args in `parameterNames` used for normalization

- .changeset/fuzzy-bats-repair.md
- packages/enoki/src/wallet/wallet.ts
Avoids calling Enoki API to create a new proof when one is already available
👀 
---
> [enoki-wallet] reuse existing proof when available

- packages/dapp-kit-next/packages/dapp-kit-core/src/core/actions/connect-wallet.ts
- packages/dapp-kit-next/packages/dapp-kit-core/src/core/actions/disconnect-wallet.ts
- packages/dapp-kit-next/packages/dapp-kit-core/src/core/index.ts
- packages/dapp-kit-next/packages/dapp-kit-core/src/core/initializers/autoconnect-wallet.ts
- packages/dapp-kit-next/packages/dapp-kit-core/src/core/initializers/sync-state-to-storage.ts
I had a little extra time, so I figured I'd try to get the remaining dApp Kit work out of the way. This PR adds the backward compatible auto-connect functionality for wallets that don't pre-populate the accounts array.
- Auto-connect works normally with all wallets (e.g. Phantom which doesn't populate accounts on load and Backpack which does)
---
> [dapp-kit-next] add backward compatible auto-connect functionality

- .changeset/sad-showers-pay.md
- packages/codegen/src/generate-utils.ts
- packages/codegen/tests/generated/utils/index.ts
- packages/suins-v2/src/calls.ts
- packages/suins-v2/src/contracts/suins_payments/payments.ts
- packages/suins-v2/src/contracts/suins_temp_subdomain_proxy/subdomain_proxy.ts
- packages/suins-v2/src/contracts/utils/index.ts
- packages/walrus/src/contracts/utils/index.ts
Optional structs should return `bcs.option` instead of `bcs.vector`
This was tested by using `codegen` for `payment-kit`
> [Codegen]  Use `bcs.option` instead of `bcs.vector`
